import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from 'next/headers';
import { auth } from '@/lib/auth';
import { Toaster } from "sonner";
import { HeroHeader } from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    const session = await auth.api.getSession({ headers: await headers() });
    const isLoggedIn = Boolean(session);
    // σε better-auth δεν χρειάζομαστε να κάνουμε χειροκίνητο έλεγχο του cookie, το session θα είναι null αν δεν υπάρχει έγκυρο token

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroHeader isLoggedIn={isLoggedIn} />
        <Toaster position="top-right" />
        <main className="pt-24">
          {children}
        </main>
      </body>
    </html>
  );
}
